### ISSUE TITLE
New precision recall job with psid db

### ISSUE THREAD

**Issue by ankurgupta-samsung** [TVServices/emr_apps#2]
Here are the changes required for the precision recall job:

-Read data from S3 files: sea-sparkjobs/prod/RecommendationLogs  & ExtraClicks 
-Join with psiddb file to get mso information. location TBD
-Add checksum for document inserted into ES so that same files can be processed again

**Comment by ankurgupta-samsung** [comment]
@vinodtalati - The location to read recommendation log and click data is 

sea-sparkjobs/prod/data/recommendationLogs or sea-sparkjobs/prod/S3WriterRecLogs/output ? 

Also, can we push one instance of psiddb file to S3. If it is already there, could you please share the location.

**Comment by vinodtalati** [comment]
raw files are under prod/data, dev/data

Psiddb file is not ready yet. Will update when ready.

**Comment by ankurgupta-samsung** [comment]
https://github.com/TVServices/emr_apps/commit/1a87d7feb417868e45bdbbac20d8009727f04311

**Comment by ankurgupta-samsung** [comment]
Sample output: 

{"id":"6a3a77ba7de100778ff3dad135b8812197b0f825ef91ea21c3a46337964861cf","duid":"H44D26LLG4DRT5OYQMPGVOPSAI7A2YSU","precision":0.0,"recall":0.0,"tile_count":0,"watch_count":0,"match_count":-1,"algoSetId":null,"processed_timestamp":"2017-03-28T13:30:00-0700","experiment":"a8a5537e-f763-4ae9-a0c7-5b8bacda406b","msoId":"1011","lineupId":"82738273","privacyFlag":true,"bucket":"A","experiment_context":"PROD","match_type":null,"experiment_creation_date":"Jan 6, 2017 4:00:43 AM","matched_list":null,"tile_position":null}
